apiVersion: v1
kind: Pod
metadata:
  name: nginx-liveness
  labels:
    test: liveness
spec:
  containers:
  - name: nginx
    image: nginx:latest
    livenessProbe:
      exec:
        command:
        - curl
        - localhost
      initialDelaySeconds: 20
      periodSeconds: 5
    ports:
    - containerPort: 8080
