apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: landingpage-clusterip
spec:
  ports:
  - port: 90
    protocol: TCP
    targetPort: 90
  selector:
    app: webserver
    environment: staging
status:
  loadBalancer: {}
