---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-volume-0
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/www-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-volume-1
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/www-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-volume-2
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:   
    path: "/mnt/data/www-2"
